BaseURL = "https://zhang-ru.github.io/blog/"
languageCode = "zh-CN"
Title = "ZR's Blog"
theme = "hyde"
disqusShortname = "spf13"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"
  

[Menus]
  main = [
      {Name = "Archives", URL = "https://zhang-ru.github.io/blog/posts/"},
      {Name = "Tags", URL = "https://zhang-ru.github.io/blog/tags/"},
      {Name = "Photos", URL = "https://zhang-ru.github.io/blog/photos/"}
  ]

[Params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description about this website
  description = "You are what you choose."



[Params.valine]
  enable = false
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true